# Generated by Django 2.1.7 on 2019-05-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='githuburl',
            field=models.CharField(default='https://github.com/j0garcia1969', max_length=100),
            preserve_default=False,
        ),
    ]
